"""web3d-M7: score every renderer against the path-traced reference.

For each scenario in cache/, compares against the reference golden
(Blender Cycles, per suite.json):
  - Twe        (out/twe/<scenario>.png, from tests/graphics_bench.rs)
  - Three.js   (out/three/<scenario>.png, from render-three.mjs)
  - the other engines' goldens fetched with the scenario

using NVIDIA's FLIP (LDR, default 67 pixels per degree), the mean of the
per-pixel error map: 0 is identical, lower is better. Transparent
backgrounds are composited over black first, as the goldens were.

Writes results.md (the table the M7 closeout publishes), results.json,
and FLIP error maps for Twe and Three.js under out/flip/.

    pip install --user flip-evaluator==1.7 numpy pillow
    python score.py            (from bench/graphics/)
"""

import json
import sys
from pathlib import Path

import flip_evaluator as flip
import numpy as np
from PIL import Image

HERE = Path(__file__).parent
SUITE = json.loads((HERE / "suite.json").read_text())
CACHE, OUT = HERE / "cache", HERE / "out"


def load(path, size):
    """An image as HxWx3 floats in [0, 1], alpha composited over black."""
    img = Image.open(path).convert("RGBA")
    if img.size != size:
        return None
    a = np.asarray(img, dtype=np.float32) / 255.0
    return a[:, :, :3] * a[:, :, 3:4]


def main():
    columns = ["twe", "three"] + SUITE["alsoScored"]
    rows = {}
    (OUT / "flip").mkdir(parents=True, exist_ok=True)
    for name in SUITE["scenarios"]:
        scene_path = CACHE / name / "scene.json"
        if not scene_path.exists():
            print(f"{name}: not fetched (node fetch.mjs)", file=sys.stderr)
            continue
        scene = json.loads(scene_path.read_text())
        size = (scene["pixels"]["width"], scene["pixels"]["height"])
        ref = load(CACHE / name / scene["goldens"][SUITE["reference"]], size)
        candidates = {
            "twe": OUT / "twe" / f"{name}.png",
            "three": OUT / "three" / f"{name}.png",
        }
        for r in SUITE["alsoScored"]:
            if r in scene["goldens"]:
                candidates[r] = CACHE / name / scene["goldens"][r]
        row = {}
        for col, path in candidates.items():
            if not path.exists():
                continue
            test = load(path, size)
            if test is None:
                print(f"{name}/{col}: size differs from the reference; skipped", file=sys.stderr)
                continue
            error_map, mean, _ = flip.evaluate(ref, test, "LDR")
            row[col] = float(mean)
            if col in ("twe", "three"):
                Image.fromarray((np.clip(error_map, 0, 1) * 255).astype(np.uint8)).save(
                    OUT / "flip" / f"{name}-{col}.png"
                )
        rows[name] = row
        print(name, "  ".join(f"{k} {v:.4f}" for k, v in row.items()))

    # The table: one row per scenario, a mean over scenarios every
    # column has, and the best score in each row in bold.
    def fmt(v, best):
        return "–" if v is None else (f"**{v:.4f}**" if v == best else f"{v:.4f}")

    names = {
        "twe": "Twe",
        "three": "Three.js",
        "model-viewer": "model-viewer*",
        "gltf-sample-viewer": "glTF Sample Viewer*",
        "filament": "Filament*",
        "babylon": "Babylon.js*",
    }
    lines = [
        "# Graphics comparison: mean FLIP error against Blender Cycles",
        "",
        "Lower is better; 0 would be identical to the path-traced reference.",
        "Generated by `bench/graphics/score.py`; see `bench/graphics/README.md`.",
        "",
        "| Scenario | " + " | ".join(names.get(c, c) for c in columns) + " |",
        "|---|" + "---:|" * len(columns),
    ]
    for name, row in rows.items():
        present = [v for v in row.values()]
        best = min(present) if present else None
        lines.append(
            f"| {name.removeprefix('khronos-')} | "
            + " | ".join(fmt(row.get(c), best) for c in columns)
            + " |"
        )
    common = [n for n, r in rows.items() if all(c in r for c in ("twe", "three"))]
    if common:
        means = {
            c: sum(rows[n][c] for n in common) / len(common)
            for c in columns
            if all(c in rows[n] for n in common)
        }
        best = min(means.values())
        lines.append(
            f"| **Mean ({len(common)} scenes)** | "
            + " | ".join(fmt(means.get(c), best) for c in columns)
            + " |"
        )
    three_revision = "0.186.1"
    lines += [
        "",
        f"Twe and Three.js (r{three_revision.split('.')[1]}, `three@{three_revision}`) are rendered by this",
        "harness from the same scenario files. Columns marked * are the goldens those",
        "engines contributed to the Khronos Render Fidelity project at generator commit",
        f"`{SUITE['generator']['commit'][:10]}`, scored the same way, for context.",
        "A dash means that engine has no golden for the scene; the mean row covers",
        "only engines with every scene.",
        "",
        "Twe renders with ambient occlusion and screen-space reflections on",
        "(`TWE_BENCH_AO`, `TWE_BENCH_SSR`); Three.js as this harness sets it up",
        "uses neither (three ships GTAOPass and SSRPass addons, not used here).",
    ]
    notes = SUITE.get("notes", {})
    if notes:
        lines += ["", "## Notes", ""]
        lines += [f"- **{n.removeprefix('khronos-')}:** {t}" for n, t in notes.items()]
    (HERE / "results.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (HERE / "results.json").write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {HERE / 'results.md'}")


if __name__ == "__main__":
    main()
