//! Phase 9 session 10: WGSL codegen for `visual` blocks.
//!
//! Turns a `visual <Name>:` declaration's `pixel(uv, time) -> color`
//! body into a complete WGSL module — vertex passthrough emitting a
//! fullscreen quad + fragment shader that calls the compiled `pixel`
//! function. The subset typechecker (`crate::visual_check`) must
//! pass first; this codegen assumes the whitelist already holds and
//! returns a `WgslError` only for shapes the subset checker would
//! also reject.
//!
//! WGSL spec touchpoints:
//! - `smoothstep(low, high, x)` matches our CPU impl (IEC piecewise
//!   Hermite curve clamped to [0,1]).
//! - `mix(a, b, t)` is the WGSL linear-interpolation builtin and
//!   matches `color.lerp` semantics on tuples.
//! - `noise()` is NOT a WGSL builtin; we emit our own value-noise
//!   helper that bit-matches the CPU `value_noise_2d` from
//!   stdlib.rs (same Wang-style hash, same golden-ratio offset, same
//!   smoothstep-weighted bilinear interp).
//!
//! Type inference is lightweight: `uv` is bound as `vec2<f32>`,
//! `time` as `f32`; tuple literals are emitted as `vec2`/`vec3`/
//! `vec4<f32>` based on element count; integer literals always
//! become `f32` so they unify with vector arithmetic without
//! per-call type analysis.

use crate::ast::{BinOp, DeclKind, DeclMember, Expr, Stmt, UnOp};
use std::fmt::Write;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WgslError {
    pub message: String,
    pub line: u32,
    pub col: u32,
}

/// Compile every `visual` block in the program. Returns a vector of
/// `(name, wgsl_source)` pairs in source order. Empty when the
/// program has no visual blocks.
pub fn compile_program(program: &crate::ast::Program) -> Result<Vec<(String, String)>, WgslError> {
    let mut out = Vec::new();
    for stmt in &program.stmts {
        if let Stmt::Decl {
            kind: DeclKind::Visual,
            name,
            members,
            ..
        } = stmt
        {
            out.push((name.clone(), compile_visual(name, members)?));
        }
    }
    Ok(out)
}

/// Compile one visual block to a WGSL module string.
pub fn compile_visual(name: &str, members: &[DeclMember]) -> Result<String, WgslError> {
    let pixel = members
        .iter()
        .find_map(|m| match m {
            DeclMember::Method {
                name: n,
                params,
                body,
                line,
                col,
                ..
            } if n == "pixel" => Some((params, body, *line, *col)),
            _ => None,
        })
        .ok_or_else(|| WgslError {
            message: format!("visual `{name}` is missing a `pixel` method"),
            line: 0,
            col: 0,
        })?;
    let (params, body, _line, _col) = pixel;
    if params.len() != 2 {
        return Err(WgslError {
            message: format!(
                "visual `{name}`: pixel takes (uv, time) — found {} params",
                params.len()
            ),
            line: 0,
            col: 0,
        });
    }
    let uv_name = &params[0].name;
    let time_name = &params[1].name;

    let mut body_src = String::new();
    let mut cx = Codegen { indent: 1 };
    for stmt in body {
        cx.emit_stmt(&mut body_src, stmt)?;
    }

    let mut out = String::new();
    writeln!(out, "// Generated by Twe — visual `{name}`. Do not edit.").unwrap();
    writeln!(out).unwrap();
    out.push_str(VS_PREAMBLE);
    out.push_str(UNIFORMS);
    out.push_str(WGSL_NOISE);
    writeln!(
        out,
        "fn twe_pixel({uv_name}: vec2<f32>, {time_name}: f32) -> vec4<f32> {{"
    )
    .unwrap();
    out.push_str(&body_src);
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    out.push_str(FS_MAIN);
    Ok(out)
}

const VS_PREAMBLE: &str = r#"struct VsOut {
    @builtin(position) pos: vec4<f32>,
    @location(0) uv: vec2<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) idx: u32) -> VsOut {
    // Fullscreen-triangle vertex_index trick — covers the whole
    // viewport in 3 verts with no buffer binding. uv runs (0,0)
    // top-left to (1,1) bottom-right (matches the rest of Twe's
    // pixel-coord convention).
    var p = vec2<f32>(f32((idx << 1u) & 2u), f32(idx & 2u));
    var out: VsOut;
    out.pos = vec4<f32>(p * 2.0 - 1.0, 0.0, 1.0);
    out.uv = vec2<f32>(p.x, 1.0 - p.y);
    return out;
}

"#;

const UNIFORMS: &str = r#"struct Uniforms {
    time: f32,
    _pad0: f32,
    _pad1: f32,
    _pad2: f32,
};
@group(0) @binding(0) var<uniform> u: Uniforms;

"#;

/// Twe-compiled noise. Bit-identical to `stdlib::value_noise_2d` so
/// CPU samples line up with shader samples. The hash uses a u32
/// pipeline (matches Rust's wrapping_mul semantics on 32-bit).
const WGSL_NOISE: &str = r#"fn twe_noise_hash2(x: i32, y: i32) -> f32 {
    var h: u32 = u32(x) * 0x27d4eb2du
                + u32(y) * 0x165667b1u
                + 0x9e3779b9u;
    h = h ^ (h >> 15u);
    h = h * 0x85ebca6bu;
    h = h ^ (h >> 13u);
    h = h * 0xc2b2ae35u;
    h = h ^ (h >> 16u);
    return (f32(h) / 4294967295.0) * 2.0 - 1.0;
}

fn noise(p: vec2<f32>) -> f32 {
    let xi = floor(p.x);
    let yi = floor(p.y);
    let xf = p.x - xi;
    let yf = p.y - yi;
    let su = xf * xf * (3.0 - 2.0 * xf);
    let sv = yf * yf * (3.0 - 2.0 * yf);
    let xii = i32(xi);
    let yii = i32(yi);
    let n00 = twe_noise_hash2(xii, yii);
    let n10 = twe_noise_hash2(xii + 1, yii);
    let n01 = twe_noise_hash2(xii, yii + 1);
    let n11 = twe_noise_hash2(xii + 1, yii + 1);
    let nx0 = n00 * (1.0 - su) + n10 * su;
    let nx1 = n01 * (1.0 - su) + n11 * su;
    return nx0 * (1.0 - sv) + nx1 * sv;
}

"#;

const FS_MAIN: &str = r#"@fragment
fn fs_main(in: VsOut) -> @location(0) vec4<f32> {
    return twe_pixel(in.uv, u.time);
}
"#;

struct Codegen {
    indent: usize,
}

impl Codegen {
    fn push_indent(&self, out: &mut String) {
        for _ in 0..self.indent {
            out.push_str("    ");
        }
    }

    fn emit_stmt(&mut self, out: &mut String, stmt: &Stmt) -> Result<(), WgslError> {
        match stmt {
            Stmt::Let { name, value, .. } => {
                self.push_indent(out);
                out.push_str("let ");
                out.push_str(name);
                out.push_str(" = ");
                self.emit_expr(out, value)?;
                out.push_str(";\n");
            }
            Stmt::Return { value: Some(e), .. } => {
                self.push_indent(out);
                out.push_str("return ");
                self.emit_expr(out, e)?;
                out.push_str(";\n");
            }
            Stmt::Return { line, col, .. } => {
                return Err(WgslError {
                    message: "bare `return` not supported in visual bodies — return a color"
                        .to_string(),
                    line: *line,
                    col: *col,
                });
            }
            Stmt::If {
                cond,
                then_body,
                elifs,
                else_body,
                ..
            } => {
                self.push_indent(out);
                out.push_str("if (");
                self.emit_expr(out, cond)?;
                out.push_str(") {\n");
                self.indent += 1;
                for s in then_body {
                    self.emit_stmt(out, s)?;
                }
                self.indent -= 1;
                self.push_indent(out);
                out.push('}');
                for (c, body) in elifs {
                    out.push_str(" else if (");
                    self.emit_expr(out, c)?;
                    out.push_str(") {\n");
                    self.indent += 1;
                    for s in body {
                        self.emit_stmt(out, s)?;
                    }
                    self.indent -= 1;
                    self.push_indent(out);
                    out.push('}');
                }
                if let Some(body) = else_body {
                    out.push_str(" else {\n");
                    self.indent += 1;
                    for s in body {
                        self.emit_stmt(out, s)?;
                    }
                    self.indent -= 1;
                    self.push_indent(out);
                    out.push('}');
                }
                out.push('\n');
            }
            Stmt::Expr(e) => {
                // Lone expression statements aren't very useful in a
                // pure shader body; emit as a discarded let to keep
                // WGSL syntactically valid and obvious to a reader.
                self.push_indent(out);
                out.push_str("let _ = ");
                self.emit_expr(out, e)?;
                out.push_str(";\n");
            }
            // The subset checker rejects everything below before we
            // get here. Belt + suspenders: surface a WgslError if
            // codegen ever sees one (would indicate a checker bug).
            _ => {
                return Err(WgslError {
                    message: "internal: visual codegen reached unsupported stmt — subset checker should have rejected this"
                        .to_string(),
                    line: 0,
                    col: 0,
                });
            }
        }
        Ok(())
    }

    fn emit_expr(&self, out: &mut String, expr: &Expr) -> Result<(), WgslError> {
        match expr {
            // Always emit numbers as f32 literals so they unify with
            // vector arithmetic without per-call type analysis. WGSL
            // requires the trailing decimal for float literals.
            Expr::Int { value, .. } => {
                write!(out, "{}.0", value).unwrap();
            }
            Expr::Float { value, .. } => {
                if value.fract() == 0.0 {
                    write!(out, "{:.1}", value).unwrap();
                } else {
                    write!(out, "{}", value).unwrap();
                }
            }
            Expr::Bool { value, .. } => {
                out.push_str(if *value { "true" } else { "false" });
            }
            Expr::Ident { name, .. } => {
                out.push_str(name);
            }
            Expr::Tuple { elems, line, col } => {
                let n = elems.len();
                let ctor = match n {
                    2 => "vec2<f32>",
                    3 => "vec3<f32>",
                    4 => "vec4<f32>",
                    _ => {
                        return Err(WgslError {
                            message: format!(
                                "tuple of {n} elements has no WGSL vector type (expected 2, 3, or 4)"
                            ),
                            line: *line,
                            col: *col,
                        });
                    }
                };
                out.push_str(ctor);
                out.push('(');
                for (i, e) in elems.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    self.emit_expr(out, e)?;
                }
                out.push(')');
            }
            Expr::Binary {
                op, left, right, ..
            } => {
                out.push('(');
                self.emit_expr(out, left)?;
                out.push(' ');
                out.push_str(binop_str(*op));
                out.push(' ');
                self.emit_expr(out, right)?;
                out.push(')');
            }
            Expr::Unary { op, operand, .. } => {
                out.push_str(unop_str(*op));
                out.push('(');
                self.emit_expr(out, operand)?;
                out.push(')');
            }
            Expr::Field {
                object,
                name,
                line,
                col,
            } => {
                // Special-case color.<named-constant> → emit the
                // RGBA tuple inline as a vec4<f32> literal so the
                // shader doesn't need a separate constants table.
                if let Expr::Ident { name: m, .. } = object.as_ref() {
                    if m == "color" {
                        if let Some(rgba) = color_constant(name) {
                            write!(
                                out,
                                "vec4<f32>({:.1}, {:.1}, {:.1}, {:.1})",
                                rgba[0], rgba[1], rgba[2], rgba[3]
                            )
                            .unwrap();
                            return Ok(());
                        }
                        return Err(WgslError {
                            message: format!("unknown `color.{name}` in visual body"),
                            line: *line,
                            col: *col,
                        });
                    }
                }
                // Generic field access: emit `(obj).field`. Used for
                // swizzles like `uv.x` and `color_value.r`.
                out.push('(');
                self.emit_expr(out, object)?;
                out.push_str(").");
                out.push_str(name);
            }
            Expr::Call {
                callee,
                args,
                line,
                col,
                ..
            } => {
                let callee_name = call_name(callee).ok_or_else(|| WgslError {
                    message: "visual codegen: unsupported callee shape".to_string(),
                    line: *line,
                    col: *col,
                })?;
                out.push_str(&callee_name);
                out.push('(');
                for (i, a) in args.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    self.emit_expr(out, a)?;
                }
                out.push(')');
            }
            other => {
                return Err(WgslError {
                    message: format!(
                        "visual codegen: unsupported expression {:?}",
                        std::mem::discriminant(other)
                    ),
                    line: other.line(),
                    col: other.col(),
                });
            }
        }
        Ok(())
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Eq => "==",
        BinOp::Neq => "!=",
        BinOp::Lt => "<",
        BinOp::Lte => "<=",
        BinOp::Gt => ">",
        BinOp::Gte => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        // `in` / `not in` aren't whitelisted by visual_check (no
        // collection literals reach here) but the match needs to be
        // exhaustive — emit `false` so a stray operator surfaces in
        // codegen rather than crashing.
        BinOp::In | BinOp::NotIn => "/* in/not-in unsupported */ ==",
    }
}

fn unop_str(op: UnOp) -> &'static str {
    match op {
        UnOp::Neg => "-",
        UnOp::Not => "!",
    }
}

/// Resolve a Twe call's callee to a WGSL function name.
/// `smoothstep` / `mix` / `noise` map 1:1 (WGSL provides smoothstep
/// and mix; we emit our own noise via the WGSL_NOISE preamble).
/// `math.<name>` maps to the matching WGSL builtin (sin, cos, etc.)
/// — every name we whitelisted in visual_check has a same-named
/// WGSL counterpart.
fn call_name(callee: &Expr) -> Option<String> {
    match callee {
        Expr::Ident { name, .. } => Some(name.clone()),
        Expr::Field { object, name, .. } => {
            if let Expr::Ident { name: m, .. } = object.as_ref() {
                if m == "math" {
                    return Some(name.clone());
                }
            }
            None
        }
        _ => None,
    }
}

/// RGBA values for the named palette in `stdlib.rs::install_color`.
/// Codegen inlines these as vec4<f32> literals so visual shaders
/// don't need a runtime constants table — `color.red` becomes
/// `vec4<f32>(1.0, 0.0, 0.0, 1.0)` directly.
fn color_constant(name: &str) -> Option<[f32; 4]> {
    Some(match name {
        "red" => [1.0, 0.0, 0.0, 1.0],
        "green" => [0.0, 1.0, 0.0, 1.0],
        "blue" => [0.0, 0.0, 1.0, 1.0],
        "cyan" => [0.0, 1.0, 1.0, 1.0],
        "yellow" => [1.0, 1.0, 0.0, 1.0],
        "orange" => [1.0, 0.5, 0.0, 1.0],
        "purple" => [0.5, 0.0, 0.5, 1.0],
        "white" => [1.0, 1.0, 1.0, 1.0],
        "black" => [0.0, 0.0, 0.0, 1.0],
        "gray" => [0.5, 0.5, 0.5, 1.0],
        "transparent" => [0.0, 0.0, 0.0, 0.0],
        _ => return None,
    })
}
