//! Phase 9 session 10: WGSL codegen for `visual` blocks.
//!
//! Turns a `visual <Name>:` declaration's methods into WGSL:
//!
//! - `pixel(uv, time) -> color` — a fullscreen fragment shader
//!   (`compile_visual`, used by `twec play_visual`) or a mesh's colour;
//! - web3d-M7: `surface(uv, time, pos, normal) -> material` — a mesh's
//!   full surface (albedo, normal, roughness, metalness, emission);
//! - web3d-M7: `displace(uv, time, pos, normal) -> vec3` — a world-space
//!   offset for each of a mesh's vertices.
//!
//! The subset typechecker (`crate::visual_check`) must pass first; this
//! codegen assumes the whitelist already holds. It does its own light
//! type inference (numbers are `f32`, tuples `vecN<f32>`, calls follow
//! the WGSL builtin's rule) so it can splat scalars where WGSL needs
//! matching types and coerce a method's result to its WGSL return
//! type; a type the method can't return is a `WgslError`, which
//! `visual_check` reports as a visual error.
//!
//! WGSL spec touchpoints:
//! - `smoothstep(low, high, x)` matches our CPU impl (IEC piecewise
//!   Hermite curve clamped to [0,1]).
//! - `mix(a, b, t)` is the WGSL linear-interpolation builtin and
//!   matches `color.lerp` semantics on tuples.
//! - `noise()` is NOT a WGSL builtin; we emit our own value-noise
//!   helper that bit-matches the CPU `value_noise_2d` from
//!   stdlib.rs (same Wang-style hash, same golden-ratio offset, same
//!   smoothstep-weighted bilinear interp).
//! - `math.mod` is Rust's `rem_euclid` (`a - |b|·floor(a / |b|)`), and
//!   `math.normalize` returns a zero vector unchanged, as on the CPU.

use crate::ast::{BinOp, DeclKind, DeclMember, Expr, Param, Stmt, UnOp};
use std::fmt::Write;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WgslError {
    pub message: String,
    pub line: u32,
    pub col: u32,
}

/// web3d-M7: the named arguments of `material(...)`, the value a
/// `surface` method returns, in `TweSurface` field order.
pub const MATERIAL_OUTPUTS: &[&str] = &["albedo", "normal", "roughness", "metalness", "emission"];

/// web3d-M7: the inputs of `surface` and `displace`, in order. A method
/// may leave off trailing ones it doesn't use.
pub const SURFACE_INPUTS: &[&str] = &["uv", "time", "pos", "normal"];

/// Compile every `visual` block in the program. Returns a vector of
/// `(name, wgsl_source)` pairs in source order. Empty when the
/// program has no visual blocks.
pub fn compile_program(program: &crate::ast::Program) -> Result<Vec<(String, String)>, WgslError> {
    let mut out = Vec::new();
    for stmt in &program.stmts {
        if let Stmt::Decl {
            kind: DeclKind::Visual,
            name,
            members,
            ..
        } = stmt
        {
            out.push((name.clone(), compile_visual(name, members)?));
        }
    }
    Ok(out)
}

/// web3d-M3 / M7: compile a visual block into the WGSL a mesh material
/// needs, for the kernel to splice into its material shader
/// (`kernel::render::material_shader_source`). It defines:
///
/// - `struct TweSurface` (albedo, normal, roughness, metalness,
///   emission);
/// - `fn twe_surface(uv: vec2<f32>, time: f32, pos: vec3<f32>,
///   normal: vec3<f32>) -> TweSurface` — the visual's `surface`, or
///   its `pixel` as the albedo of the plain surface (roughness 0.5,
///   dielectric);
/// - `fn twe_displace(...) -> vec3<f32>` with the same inputs, only
///   when the visual has a `displace` method (the kernel draws the
///   material with its displacing vertex stage when it's there).
///
/// Colours are as scripts write them (sRGB); the kernel decodes them.
pub fn compile_material(name: &str, members: &[DeclMember]) -> Result<String, WgslError> {
    let pixel = find_method(members, "pixel");
    let surface = find_method(members, "surface");
    let mut out = String::new();
    writeln!(out, "// Generated by Twe — visual `{name}` as a material.").unwrap();
    out.push_str(MATERIAL_STRUCT);
    out.push_str(WGSL_NOISE);
    match (pixel, surface) {
        (Some(_), Some(_)) => {
            return Err(WgslError {
                message: format!("visual `{name}` has both `pixel` and `surface` — keep one"),
                line: 0,
                col: 0,
            });
        }
        (Some(_), None) => {
            out.push_str(&pixel_fn(name, members)?);
            out.push_str(PIXEL_AS_SURFACE);
        }
        (None, Some(m)) => out.push_str(&method_fn(m, Ret::Material)?),
        (None, None) => {
            return Err(WgslError {
                message: format!("visual `{name}` is missing a `pixel` or `surface` method"),
                line: 0,
                col: 0,
            });
        }
    }
    if let Some(m) = find_method(members, "displace") {
        out.push_str(&method_fn(m, Ret::Offset)?);
    }
    Ok(out)
}

/// A visual method's parameters, body and position.
struct Method<'a> {
    name: &'a str,
    params: &'a [Param],
    body: &'a [Stmt],
    line: u32,
    col: u32,
}

fn find_method<'a>(members: &'a [DeclMember], wanted: &str) -> Option<Method<'a>> {
    members.iter().find_map(|m| match m {
        DeclMember::Method {
            name,
            params,
            body,
            line,
            col,
            ..
        } if name == wanted => Some(Method {
            name,
            params,
            body,
            line: *line,
            col: *col,
        }),
        _ => None,
    })
}

/// The `twe_pixel` function for a visual block.
fn pixel_fn(name: &str, members: &[DeclMember]) -> Result<String, WgslError> {
    let m = find_method(members, "pixel").ok_or_else(|| WgslError {
        message: format!("visual `{name}` is missing a `pixel` method"),
        line: 0,
        col: 0,
    })?;
    if m.params.len() != 2 {
        return Err(WgslError {
            message: format!(
                "visual `{name}`: pixel takes (uv, time) — found {} params",
                m.params.len()
            ),
            line: m.line,
            col: m.col,
        });
    }
    method_fn(m, Ret::Color)
}

/// What a method returns, and so its WGSL function.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Ret {
    /// `pixel`: a colour, `vec4<f32>`.
    Color,
    /// `surface`: `material(...)`, a `TweSurface`.
    Material,
    /// `displace`: a world-space offset, `vec3<f32>`.
    Offset,
}

/// Compile one method to its WGSL function. `pixel` takes (uv, time);
/// `surface` and `displace` take the four `SURFACE_INPUTS`, and inputs
/// the method leaves off get internal names.
fn method_fn(m: Method<'_>, ret: Ret) -> Result<String, WgslError> {
    let (fn_name, ret_ty, inputs) = match ret {
        Ret::Color => ("twe_pixel", "vec4<f32>", 2),
        Ret::Material => ("twe_surface", "TweSurface", 4),
        Ret::Offset => ("twe_displace", "vec3<f32>", 4),
    };
    if m.params.len() < 2 || m.params.len() > inputs {
        return Err(WgslError {
            message: format!(
                "`{}` takes ({}) — found {} params",
                m.name,
                SURFACE_INPUTS[..inputs].join(", "),
                m.params.len()
            ),
            line: m.line,
            col: m.col,
        });
    }
    let input_tys = [Ty::Vec(2), Ty::F32, Ty::Vec(3), Ty::Vec(3)];
    let wgsl_tys = ["vec2<f32>", "f32", "vec3<f32>", "vec3<f32>"];
    let mut cx = Codegen {
        indent: 1,
        scope: Vec::new(),
        ret,
        normal_in: String::new(),
    };
    let mut sig = Vec::new();
    for i in 0..inputs {
        let name = m
            .params
            .get(i)
            .map(|p| p.name.clone())
            .unwrap_or_else(|| format!("twe_{}", SURFACE_INPUTS[i]));
        sig.push(format!("{name}: {}", wgsl_tys[i]));
        if i == 3 {
            cx.normal_in = name.clone();
        }
        cx.scope.push((name, input_tys[i]));
    }
    let mut body = String::new();
    for stmt in m.body {
        cx.emit_stmt(&mut body, stmt)?;
    }
    let mut out = String::new();
    writeln!(out, "fn {fn_name}({}) -> {ret_ty} {{", sig.join(", ")).unwrap();
    out.push_str(&body);
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(out)
}

/// Compile one visual block to a WGSL module string.
pub fn compile_visual(name: &str, members: &[DeclMember]) -> Result<String, WgslError> {
    if let (None, Some(m)) = (find_method(members, "pixel"), find_method(members, "surface")) {
        return Err(WgslError {
            message: format!(
                "visual `{name}` is a `surface` material: draw it on a mesh with a look's `material: {name}` (a fullscreen visual needs `pixel`)"
            ),
            line: m.line,
            col: m.col,
        });
    }
    let mut out = String::new();
    writeln!(out, "// Generated by Twe — visual `{name}`. Do not edit.").unwrap();
    writeln!(out).unwrap();
    out.push_str(VS_PREAMBLE);
    out.push_str(UNIFORMS);
    out.push_str(WGSL_NOISE);
    out.push_str(&pixel_fn(name, members)?);
    out.push_str(FS_MAIN);
    Ok(out)
}

const VS_PREAMBLE: &str = r#"struct VsOut {
    @builtin(position) pos: vec4<f32>,
    @location(0) uv: vec2<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) idx: u32) -> VsOut {
    // Fullscreen-triangle vertex_index trick — covers the whole
    // viewport in 3 verts with no buffer binding. uv runs (0,0)
    // top-left to (1,1) bottom-right (matches the rest of Twe's
    // pixel-coord convention).
    var p = vec2<f32>(f32((idx << 1u) & 2u), f32(idx & 2u));
    var out: VsOut;
    out.pos = vec4<f32>(p * 2.0 - 1.0, 0.0, 1.0);
    out.uv = vec2<f32>(p.x, 1.0 - p.y);
    return out;
}

"#;

const UNIFORMS: &str = r#"struct Uniforms {
    time: f32,
    _pad0: f32,
    _pad1: f32,
    _pad2: f32,
};
@group(0) @binding(0) var<uniform> u: Uniforms;

"#;

/// web3d-M7: what a material's `twe_surface` returns.
const MATERIAL_STRUCT: &str = r#"struct TweSurface {
    albedo: vec4<f32>,
    normal: vec3<f32>,
    roughness: f32,
    metalness: f32,
    emission: vec3<f32>,
};

"#;

/// web3d-M7: a `pixel` visual as a material: its colour on the plain
/// dielectric surface.
const PIXEL_AS_SURFACE: &str = r#"fn twe_surface(uv: vec2<f32>, time: f32, pos: vec3<f32>, normal: vec3<f32>) -> TweSurface {
    return TweSurface(twe_pixel(uv, time), normal, 0.5, 0.0, vec3<f32>(0.0));
}

"#;

/// Twe-compiled noise. Bit-identical to `stdlib::value_noise_2d` so
/// CPU samples line up with shader samples. The hash uses a u32
/// pipeline (matches Rust's wrapping_mul semantics on 32-bit).
pub(crate) const WGSL_NOISE: &str = r#"fn twe_noise_hash2(x: i32, y: i32) -> f32 {
    var h: u32 = u32(x) * 0x27d4eb2du
                + u32(y) * 0x165667b1u
                + 0x9e3779b9u;
    h = h ^ (h >> 15u);
    h = h * 0x85ebca6bu;
    h = h ^ (h >> 13u);
    h = h * 0xc2b2ae35u;
    h = h ^ (h >> 16u);
    return (f32(h) / 4294967295.0) * 2.0 - 1.0;
}

fn noise(p: vec2<f32>) -> f32 {
    let xi = floor(p.x);
    let yi = floor(p.y);
    let xf = p.x - xi;
    let yf = p.y - yi;
    let su = xf * xf * (3.0 - 2.0 * xf);
    let sv = yf * yf * (3.0 - 2.0 * yf);
    let xii = i32(xi);
    let yii = i32(yi);
    let n00 = twe_noise_hash2(xii, yii);
    let n10 = twe_noise_hash2(xii + 1, yii);
    let n01 = twe_noise_hash2(xii, yii + 1);
    let n11 = twe_noise_hash2(xii + 1, yii + 1);
    let nx0 = n00 * (1.0 - su) + n10 * su;
    let nx1 = n01 * (1.0 - su) + n11 * su;
    return nx0 * (1.0 - sv) + nx1 * sv;
}

"#;

const FS_MAIN: &str = r#"@fragment
fn fs_main(in: VsOut) -> @location(0) vec4<f32> {
    return twe_pixel(in.uv, u.time);
}
"#;

/// The WGSL type of a visual-body value.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Ty {
    F32,
    /// `vecN<f32>`, N = 2..4.
    Vec(u8),
    Bool,
    /// `material(...)`: a `TweSurface`.
    Material,
}

impl Ty {
    fn describe(self) -> String {
        match self {
            Ty::F32 => "a number".to_string(),
            Ty::Vec(n) => format!("a {n}-tuple"),
            Ty::Bool => "a bool".to_string(),
            Ty::Material => "a material".to_string(),
        }
    }
}

/// The wider of two numeric types (a scalar splats to a vector).
fn widest(a: Ty, b: Ty) -> Ty {
    match (a, b) {
        (Ty::Vec(x), Ty::Vec(y)) => Ty::Vec(x.max(y)),
        (Ty::Vec(x), _) | (_, Ty::Vec(x)) => Ty::Vec(x),
        _ => a,
    }
}

struct Codegen {
    indent: usize,
    /// Names in scope and their types: the inputs, then `let`s.
    scope: Vec<(String, Ty)>,
    ret: Ret,
    /// The WGSL name of the `normal` input (`material`'s default).
    normal_in: String,
}

fn err(message: String, line: u32, col: u32) -> WgslError {
    WgslError { message, line, col }
}

impl Codegen {
    fn push_indent(&self, out: &mut String) {
        for _ in 0..self.indent {
            out.push_str("    ");
        }
    }

    fn block(&mut self, out: &mut String, body: &[Stmt]) -> Result<(), WgslError> {
        let depth = self.scope.len();
        self.indent += 1;
        for s in body {
            self.emit_stmt(out, s)?;
        }
        self.indent -= 1;
        self.scope.truncate(depth);
        Ok(())
    }

    fn emit_stmt(&mut self, out: &mut String, stmt: &Stmt) -> Result<(), WgslError> {
        match stmt {
            Stmt::Let { name, value, .. } => {
                let ty = self.ty_of(value)?;
                if ty == Ty::Material {
                    return Err(err(
                        "`material(...)` can only be returned, not bound to a name".to_string(),
                        value.line(),
                        value.col(),
                    ));
                }
                self.push_indent(out);
                out.push_str("let ");
                out.push_str(name);
                out.push_str(" = ");
                self.emit_expr(out, value)?;
                out.push_str(";\n");
                self.scope.push((name.clone(), ty));
            }
            Stmt::Return { value: Some(e), .. } => {
                self.push_indent(out);
                out.push_str("return ");
                self.emit_return(out, e)?;
                out.push_str(";\n");
            }
            Stmt::Return { line, col, .. } => {
                let what = match self.ret {
                    Ret::Color => "a color",
                    Ret::Material => "`material(...)`",
                    Ret::Offset => "an (x, y, z) offset",
                };
                return Err(err(
                    format!("bare `return` not supported in visual bodies — return {what}"),
                    *line,
                    *col,
                ));
            }
            Stmt::If {
                cond,
                then_body,
                elifs,
                else_body,
                ..
            } => {
                self.push_indent(out);
                out.push_str("if (");
                self.emit_expr(out, cond)?;
                out.push_str(") {\n");
                self.block(out, then_body)?;
                self.push_indent(out);
                out.push('}');
                for (c, body) in elifs {
                    out.push_str(" else if (");
                    self.emit_expr(out, c)?;
                    out.push_str(") {\n");
                    self.block(out, body)?;
                    self.push_indent(out);
                    out.push('}');
                }
                if let Some(body) = else_body {
                    out.push_str(" else {\n");
                    self.block(out, body)?;
                    self.push_indent(out);
                    out.push('}');
                }
                out.push('\n');
            }
            Stmt::Expr(e) => {
                // Lone expression statements aren't very useful in a
                // pure shader body; emit as a phony assignment to keep
                // WGSL syntactically valid and obvious to a reader.
                self.push_indent(out);
                out.push_str("_ = ");
                self.emit_expr(out, e)?;
                out.push_str(";\n");
            }
            // The subset checker rejects everything below before we
            // get here. Belt + suspenders: surface a WgslError if
            // codegen ever sees one (would indicate a checker bug).
            _ => {
                return Err(err(
                    "internal: visual codegen reached unsupported stmt — subset checker should have rejected this"
                        .to_string(),
                    0,
                    0,
                ));
            }
        }
        Ok(())
    }

    /// A `return`'s value, coerced to the method's WGSL return type.
    fn emit_return(&self, out: &mut String, e: &Expr) -> Result<(), WgslError> {
        let ty = self.ty_of(e)?;
        match (self.ret, ty) {
            (Ret::Color, _) => self.emit_color(out, e, "the color `pixel` returns"),
            (Ret::Material, Ty::Material) => self.emit_expr(out, e),
            (Ret::Material, _) => Err(err(
                format!("`surface` returns `material(...)`, not {}", ty.describe()),
                e.line(),
                e.col(),
            )),
            (Ret::Offset, Ty::Vec(3)) => self.emit_expr(out, e),
            (Ret::Offset, _) => Err(err(
                format!(
                    "`displace` returns an (x, y, z) offset, not {} — e.g. `return normal * 0.1`",
                    ty.describe()
                ),
                e.line(),
                e.col(),
            )),
        }
    }

    /// A colour as `vec4<f32>`: `(r, g, b)` gains alpha 1, and a
    /// number is a grey.
    fn emit_color(&self, out: &mut String, e: &Expr, what: &str) -> Result<(), WgslError> {
        match self.ty_of(e)? {
            Ty::Vec(4) => self.emit_expr(out, e),
            Ty::Vec(3) => {
                out.push_str("vec4<f32>(");
                self.emit_expr(out, e)?;
                out.push_str(", 1.0)");
                Ok(())
            }
            Ty::F32 => {
                out.push_str("vec4<f32>(vec3<f32>(");
                self.emit_expr(out, e)?;
                out.push_str("), 1.0)");
                Ok(())
            }
            ty => Err(err(
                format!("{what} must be a color (r, g, b) or (r, g, b, a), not {}", ty.describe()),
                e.line(),
                e.col(),
            )),
        }
    }

    /// `e` as type `to`, splatting a scalar to a vector.
    fn emit_as(&self, out: &mut String, e: &Expr, to: Ty) -> Result<(), WgslError> {
        match (self.ty_of(e)?, to) {
            (Ty::F32, Ty::Vec(n)) => {
                write!(out, "vec{n}<f32>(").unwrap();
                self.emit_expr(out, e)?;
                out.push(')');
                Ok(())
            }
            _ => self.emit_expr(out, e),
        }
    }

    fn lookup(&self, name: &str) -> Option<Ty> {
        self.scope.iter().rev().find(|(n, _)| n == name).map(|(_, t)| *t)
    }

    /// The WGSL type of `expr`.
    fn ty_of(&self, expr: &Expr) -> Result<Ty, WgslError> {
        Ok(match expr {
            Expr::Int { .. } | Expr::Float { .. } => Ty::F32,
            Expr::Bool { .. } => Ty::Bool,
            Expr::Ident { name, line, col, .. } => self.lookup(name).ok_or_else(|| {
                err(
                    format!("unknown name `{name}` in a visual body"),
                    *line,
                    *col,
                )
            })?,
            Expr::Tuple { elems, line, col } => match elems.len() {
                n @ 2..=4 => Ty::Vec(n as u8),
                n => {
                    return Err(err(
                        format!("tuple of {n} elements has no WGSL vector type (expected 2, 3, or 4)"),
                        *line,
                        *col,
                    ));
                }
            },
            Expr::Binary {
                op, left, right, ..
            } => match op {
                BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Div => {
                    widest(self.ty_of(left)?, self.ty_of(right)?)
                }
                _ => Ty::Bool,
            },
            Expr::Unary { op, operand, .. } => match op {
                UnOp::Neg => self.ty_of(operand)?,
                UnOp::Not => Ty::Bool,
            },
            Expr::IfExpr {
                then_expr,
                elifs,
                else_expr,
                ..
            } => {
                let mut ty = widest(self.ty_of(then_expr)?, self.ty_of(else_expr)?);
                for (_, e) in elifs {
                    ty = widest(ty, self.ty_of(e)?);
                }
                ty
            }
            Expr::Field { object, name, .. } => {
                if let Expr::Ident { name: m, .. } = object.as_ref() {
                    if m == "color" {
                        return Ok(Ty::Vec(4));
                    }
                    if m == "math" && name == "pi" {
                        return Ok(Ty::F32);
                    }
                }
                match name.len() {
                    1 => Ty::F32,
                    n => Ty::Vec(n.min(4) as u8),
                }
            }
            Expr::Call {
                callee,
                args,
                line,
                col,
                ..
            } => {
                let name = call_name(callee).unwrap_or_default();
                let arg = |i: usize| -> Result<Ty, WgslError> {
                    args.get(i)
                        .map(|a| self.ty_of(a))
                        .unwrap_or(Err(err(format!("`{name}` is missing an argument"), *line, *col)))
                };
                match name.as_str() {
                    "material" => Ty::Material,
                    "noise" | "dot" | "length" | "atan2" => Ty::F32,
                    "cross" => Ty::Vec(3),
                    "smoothstep" => widest(widest(arg(0)?, arg(1)?), arg(2)?),
                    "mix" => widest(arg(0)?, arg(1)?),
                    "min" | "max" | "mod" => widest(arg(0)?, arg(1)?),
                    "clamp" => widest(widest(arg(0)?, arg(1)?), arg(2)?),
                    _ => arg(0)?,
                }
            }
            other => {
                return Err(err(
                    "visual codegen: unsupported expression".to_string(),
                    other.line(),
                    other.col(),
                ));
            }
        })
    }

    fn emit_expr(&self, out: &mut String, expr: &Expr) -> Result<(), WgslError> {
        match expr {
            // Always emit numbers as f32 literals so they unify with
            // vector arithmetic. WGSL requires the trailing decimal for
            // float literals.
            Expr::Int { value, .. } => {
                write!(out, "{}.0", value).unwrap();
            }
            Expr::Float { value, .. } => {
                if value.fract() == 0.0 {
                    write!(out, "{:.1}", value).unwrap();
                } else {
                    write!(out, "{}", value).unwrap();
                }
            }
            Expr::Bool { value, .. } => {
                out.push_str(if *value { "true" } else { "false" });
            }
            Expr::Ident { name, .. } => {
                out.push_str(name);
            }
            Expr::Tuple { elems, .. } => {
                let Ty::Vec(n) = self.ty_of(expr)? else {
                    unreachable!("a tuple's type is a vector");
                };
                write!(out, "vec{n}<f32>(").unwrap();
                for (i, e) in elems.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    self.emit_expr(out, e)?;
                }
                out.push(')');
            }
            Expr::Binary {
                op, left, right, ..
            } => {
                out.push('(');
                self.emit_expr(out, left)?;
                out.push(' ');
                out.push_str(binop_str(*op));
                out.push(' ');
                self.emit_expr(out, right)?;
                out.push(')');
            }
            Expr::Unary { op, operand, .. } => {
                out.push_str(unop_str(*op));
                out.push('(');
                self.emit_expr(out, operand)?;
                out.push(')');
            }
            Expr::IfExpr {
                cond,
                then_expr,
                elifs,
                else_expr,
                ..
            } => {
                // `select(false_value, true_value, cond)`, nested for
                // each `elif`, every branch splatted to the widest.
                let ty = self.ty_of(expr)?;
                let mut conds: Vec<(&Expr, &Expr)> = vec![(cond.as_ref(), then_expr.as_ref())];
                conds.extend(elifs.iter().map(|(c, e)| (c, e)));
                for _ in &conds {
                    out.push_str("select(");
                }
                self.emit_as(out, else_expr, ty)?;
                for (c, e) in conds.iter().rev() {
                    out.push_str(", ");
                    self.emit_as(out, e, ty)?;
                    out.push_str(", ");
                    self.emit_expr(out, c)?;
                    out.push(')');
                }
            }
            Expr::Field {
                object,
                name,
                line,
                col,
            } => {
                // Special-case color.<named-constant> → emit the
                // RGBA tuple inline as a vec4<f32> literal so the
                // shader doesn't need a separate constants table.
                if let Expr::Ident { name: m, .. } = object.as_ref() {
                    if m == "color" {
                        if let Some(rgba) = color_constant(name) {
                            write!(
                                out,
                                "vec4<f32>({:.1}, {:.1}, {:.1}, {:.1})",
                                rgba[0], rgba[1], rgba[2], rgba[3]
                            )
                            .unwrap();
                            return Ok(());
                        }
                        return Err(err(format!("unknown `color.{name}` in visual body"), *line, *col));
                    }
                    if m == "math" && name == "pi" {
                        out.push_str("3.14159265");
                        return Ok(());
                    }
                }
                // Generic field access: emit `(obj).field`. Used for
                // swizzles like `uv.x` and `color_value.r`.
                out.push('(');
                self.emit_expr(out, object)?;
                out.push_str(").");
                out.push_str(name);
            }
            Expr::Call {
                callee,
                args,
                kwargs,
                line,
                col,
            } => {
                let name = call_name(callee)
                    .ok_or_else(|| err("visual codegen: unsupported callee shape".to_string(), *line, *col))?;
                self.emit_call(out, &name, args, kwargs, *line, *col)?;
            }
            other => {
                return Err(err(
                    format!(
                        "visual codegen: unsupported expression {:?}",
                        std::mem::discriminant(other)
                    ),
                    other.line(),
                    other.col(),
                ));
            }
        }
        Ok(())
    }

    fn emit_call(
        &self,
        out: &mut String,
        name: &str,
        args: &[Expr],
        kwargs: &[(String, Expr)],
        line: u32,
        col: u32,
    ) -> Result<(), WgslError> {
        let arity = match name {
            "material" => 0,
            "smoothstep" | "mix" | "clamp" => 3,
            "min" | "max" | "mod" | "atan2" | "dot" | "cross" => 2,
            _ => 1,
        };
        if args.len() != arity {
            return Err(err(
                format!("`{name}` takes {arity} argument(s), got {}", args.len()),
                line,
                col,
            ));
        }
        let tys = args.iter().map(|a| self.ty_of(a)).collect::<Result<Vec<_>, _>>()?;
        let all = tys.iter().fold(Ty::F32, |a, &b| widest(a, b));
        let list = |out: &mut String, to: Option<Ty>| -> Result<(), WgslError> {
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                match to {
                    Some(t) => self.emit_as(out, a, t)?,
                    None => self.emit_expr(out, a)?,
                }
            }
            Ok(())
        };
        let need_vector = |what: &str| -> Result<(), WgslError> {
            if tys.iter().any(|t| !matches!(t, Ty::Vec(_))) {
                return Err(err(format!("`math.{name}` takes {what}"), line, col));
            }
            Ok(())
        };
        match name {
            "material" => return self.emit_material(out, kwargs),
            // Rust's rem_euclid, as `math.mod` on the CPU.
            "mod" => {
                let (a, b) = (&args[0], &args[1]);
                out.push('(');
                self.emit_as(out, a, all)?;
                out.push_str(" - abs(");
                self.emit_as(out, b, all)?;
                out.push_str(") * floor(");
                self.emit_as(out, a, all)?;
                out.push_str(" / abs(");
                self.emit_as(out, b, all)?;
                out.push_str(")))");
                return Ok(());
            }
            // A zero vector stays zero, as `math.normalize` on the CPU.
            "normalize" => {
                need_vector("a 2-, 3- or 4-tuple")?;
                let mut v = String::new();
                self.emit_expr(&mut v, &args[0])?;
                write!(out, "select({v}, normalize({v}), dot({v}, {v}) > 1e-24)").unwrap();
                return Ok(());
            }
            "dot" | "length" => need_vector("tuples")?,
            "cross" => {
                if tys.iter().any(|t| *t != Ty::Vec(3)) {
                    return Err(err("`math.cross` takes two (x, y, z) tuples".to_string(), line, col));
                }
            }
            "noise" => {
                if tys != [Ty::Vec(2)] {
                    return Err(err("`noise` takes one (x, y) point".to_string(), line, col));
                }
            }
            _ => {}
        }
        out.push_str(name);
        out.push('(');
        match name {
            // WGSL wants one type across these arguments.
            "smoothstep" | "min" | "max" | "clamp" | "atan2" => list(out, Some(all))?,
            // mix(a, b, t): a and b alike, t a number or the same.
            "mix" => {
                let ab = widest(tys[0], tys[1]);
                self.emit_as(out, &args[0], ab)?;
                out.push_str(", ");
                self.emit_as(out, &args[1], ab)?;
                out.push_str(", ");
                self.emit_expr(out, &args[2])?;
            }
            _ => list(out, None)?,
        }
        out.push(')');
        Ok(())
    }

    /// `material(albedo:, normal:, roughness:, metalness:, emission:)`
    /// as a `TweSurface`, with a default for each output left out.
    fn emit_material(&self, out: &mut String, kwargs: &[(String, Expr)]) -> Result<(), WgslError> {
        let get = |k: &str| kwargs.iter().find(|(n, _)| n == k).map(|(_, e)| e);
        out.push_str("TweSurface(");
        match get("albedo") {
            Some(e) => self.emit_color(out, e, "`albedo`")?,
            None => out.push_str("vec4<f32>(1.0)"),
        }
        out.push_str(", ");
        match get("normal") {
            Some(e) if self.ty_of(e)? == Ty::Vec(3) => {
                out.push_str("normalize(");
                self.emit_expr(out, e)?;
                out.push(')');
            }
            Some(e) => {
                return Err(err(
                    format!("`normal` must be an (x, y, z) direction, not {}", self.ty_of(e)?.describe()),
                    e.line(),
                    e.col(),
                ));
            }
            None => out.push_str(&self.normal_in),
        }
        for (key, default) in [("roughness", "0.5"), ("metalness", "0.0")] {
            out.push_str(", ");
            match get(key) {
                Some(e) if self.ty_of(e)? == Ty::F32 => {
                    out.push_str("clamp(");
                    self.emit_expr(out, e)?;
                    out.push_str(", 0.0, 1.0)");
                }
                Some(e) => {
                    return Err(err(
                        format!("`{key}` must be a number from 0 to 1, not {}", self.ty_of(e)?.describe()),
                        e.line(),
                        e.col(),
                    ));
                }
                None => out.push_str(default),
            }
        }
        out.push_str(", ");
        match get("emission") {
            Some(e) => match self.ty_of(e)? {
                Ty::F32 => {
                    out.push_str("vec3<f32>(");
                    self.emit_expr(out, e)?;
                    out.push(')');
                }
                Ty::Vec(3) => self.emit_expr(out, e)?,
                Ty::Vec(4) => {
                    out.push('(');
                    self.emit_expr(out, e)?;
                    out.push_str(").rgb");
                }
                ty => {
                    return Err(err(
                        format!("`emission` must be a color (r, g, b), not {}", ty.describe()),
                        e.line(),
                        e.col(),
                    ));
                }
            },
            None => out.push_str("vec3<f32>(0.0)"),
        }
        out.push(')');
        Ok(())
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Eq => "==",
        BinOp::Neq => "!=",
        BinOp::Lt => "<",
        BinOp::Lte => "<=",
        BinOp::Gt => ">",
        BinOp::Gte => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        // `in` / `not in` aren't whitelisted by visual_check (no
        // collection literals reach here) but the match needs to be
        // exhaustive — emit `false` so a stray operator surfaces in
        // codegen rather than crashing.
        BinOp::In | BinOp::NotIn => "/* in/not-in unsupported */ ==",
    }
}

fn unop_str(op: UnOp) -> &'static str {
    match op {
        UnOp::Neg => "-",
        UnOp::Not => "!",
    }
}

/// Resolve a Twe call's callee to a WGSL function name.
/// `smoothstep` / `mix` / `noise` / `material` are bare names;
/// `math.<name>` maps to the matching WGSL builtin (sin, cos, etc.)
/// or, for `mod` and `normalize`, to code matching the CPU.
fn call_name(callee: &Expr) -> Option<String> {
    match callee {
        Expr::Ident { name, .. } => Some(name.clone()),
        Expr::Field { object, name, .. } => {
            if let Expr::Ident { name: m, .. } = object.as_ref() {
                if m == "math" {
                    return Some(name.clone());
                }
            }
            None
        }
        _ => None,
    }
}

/// RGBA values for the named palette in `stdlib.rs::install_color`.
/// Codegen inlines these as vec4<f32> literals so visual shaders
/// don't need a runtime constants table — `color.red` becomes
/// `vec4<f32>(1.0, 0.0, 0.0, 1.0)` directly.
pub(crate) fn color_constant(name: &str) -> Option<[f32; 4]> {
    Some(match name {
        "red" => [1.0, 0.0, 0.0, 1.0],
        "green" => [0.0, 1.0, 0.0, 1.0],
        "blue" => [0.0, 0.0, 1.0, 1.0],
        "cyan" => [0.0, 1.0, 1.0, 1.0],
        "yellow" => [1.0, 1.0, 0.0, 1.0],
        "orange" => [1.0, 0.5, 0.0, 1.0],
        "purple" => [0.5, 0.0, 0.5, 1.0],
        "white" => [1.0, 1.0, 1.0, 1.0],
        "black" => [0.0, 0.0, 0.0, 1.0],
        "gray" => [0.5, 0.5, 0.5, 1.0],
        "transparent" => [0.0, 0.0, 0.0, 0.0],
        _ => return None,
    })
}
